input:
  resource: skirthooks

pipeline:
  processors:
    - bloblang: |
        let name = this.payload.chat.thread.events.0.fields.0.value.split(" ")
        firstName = $name.slice(0, 1).join("")
        lastName = $name.slice(1).join(" ")

        email = this.payload.chat.thread.events.0.fields.1.value
    - branch:
        processors:
          - http:
              url: 'https://api.capsulecrm.com/api/v2/parties/search?q=${! json("email")}'
              verb: GET
              headers:
                Content-Type: application/json
                Authorization: "Bearer ${CAPSULE_API_TOKEN}"
        result_map: |
          userExists = this.parties.length()
    - bloblang: |
        root = if this.userExists > 0 {
          deleted()
        }
    - bloblang: |
        party = {
          "type": "person",
          "firstName": this.firstName,
          "lastName": this.lastName,
          "emailAddresses": [{
            "type": "Work",
            "address": this.email
          }],
          "tags": [{
            "name": "Lead"
          }]
        }

output:
  label: "capsule_crm_output"
  http_client:
    url: https://api.capsulecrm.com/api/v2/parties
    verb: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer ${CAPSULE_API_TOKEN}"
