input:
  mqtt:
    urls:
      - tcp://${MQTT_URL}
    topics:
      - ${LC_USER}/incoming_chat
    qos: 2
    client_id: ce-benthos-processor
    dynamic_client_id_suffix: nanoid
    user: ${LC_USER}
    password: "${LC_PASSWORD}"

pipeline:
  processors:
    - bloblang: |
        root = if action != "incoming_chat" {
          deleted()
        }

    - bloblang: |
        root.content = "Hey @everyone! Someone engaged to a chat on our website. Take a look!"
        root.components = [
          {
            "type": 1,
            "components": [
              {
                "label": "Open chat",
                "type": 2,
                "style": 5,
                "url": "https://my.livechatinc.com/chats/" + this.payload.chat.id + "/" + this.payload.chat.thread.id
              }
            ]
          }
        ]

output:
  resource: discord_notifications
